### ISSUE TITLE
Create Searchbar class in views.py & make Serializer for Searchbar in dataserializers.py

### ISSUE THREAD

**Issue by BugEmir** [EmirhanSarikaya/educoding-backend-django#1]
# I can't seem to make the search function work properly and also need a serializer for it so it can translate the data from the model to our views.py

`#class SearchCourse(APIView):
  #  def get(provide, request, searchString):
        #matches = 
        #searchbar afmaken 
        # serializer maken voor searchbar`

You can take a look at courses/views.py and proceed to try.

**Comment by EmirhanSarikaya** [comment]
`class SearchCourse(APIView): #{
    def get(self, request, searchWords_lookup_from_q): #{
        #print(searchWords_lookup_from_q)
        matches = Course.objects.filter(Q(title__icontains=searchWords_lookup_from_q) | Q(desc__icontains=searchWords_lookup_from_q))
        #print(matches)
        serialized = CourseListSerializer(matches, many = True)
        return Response(data = serialized.data, status = status.HTTP_200_OK)
        #}
#}
`

**Comment by BugEmir** [comment]
never mind it.
